### ISSUE TITLE
[bug]: added SSH public keys are not respected on LAN

### ISSUE THREAD

**Issue by nall** [Start9Labs/gitea-wrapper#7]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.6.1

### Browser

Brave

### Browser Version

1.45.123

### Current Behavior

The short of it is SSH authentication to gitea on LAN seems broken out of the box. Details below.

From a chat with David Croisant:
> I basically just made an initial repo, did a ssh-keygen -t ed25519 -C blah on my local machine. Added the .pub contents to gitea, and tried an SSH clone of the repo on the LAN side
> 
> So I'm doing git clone git@1234.local:stuntaz/junk.git on the macOS side. But there's no git user on embassy, so I'm unclear how it's supposed to work.
> 
> I should add that I added an entry in my macOS $HOME/.ssh/config for
```
Host 1234.local
    IdentityFile ~/.ssh/my_priv_key
```

Ultimately the publickey authentication fails and I get prompted for a password which I believe is wrong. It should authenticate against the public key I added to gitea and specified in my `$HOME/.ssh/config`.

From `env GIT_SSH_COMMAND="ssh -vvv" git clone git@MyHost.local:MyUser/MyRepo.git` I get output like:

```
debug3: send packet: type 50 debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51 debug1: Authentications that can continue: publickey,password
debug2: we did not send a packet, disable method debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password debug1: Next authentication method: password`
git@MyHost.local's password:
```

and it asks for password. On the sshd side (I added logging to the config) I see 

```
debug2: userauth_pubkey: invalid user git querying public key ssh-ed25519 ...
debug1: userauth_pubkey: test pkalg ssh-ed25519 pkblob ED25519 ... [preauth]
debug2: userauth_pubkey: disabled because of invalid user [preauth] ...
```

### Expected Behavior

The git clone via ssh should work if the proper public key has been added to gitea

### Steps to Reproduce

Described above.

**Comment by chrisguida** [comment]
SSH over .local isn't supported because .local doesn't support non-HTTP protocols. See [this issue](https://github.com/Start9Labs/embassy-os/issues/1148) for more details. We will be implementing a port forwarding feature this year that will work around this limitation.

Closing, please reopen if I misinterpreted this issue.
